# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 170934128644403668ad51b682d0d8c733778730b1f44d67282e7be1b240cdbea518ac19e7d4b31288c1ca803d0433c4cba0c01dcb77813d8a18747812b832b3

test:
  secret_key_base: b440f7a6eb7ef257ce885e2e8624a4543765f9e4821cd21d4a6aab1971d694c4b26143b1f02e495134c42d5d3b4c30c671250614cf712b76e83602a5751ee9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
